<?php

$title = 'Delete equipment';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title);?></h1>

<p>Are you sure that you want to delete equipment
    '<em><?php echo $this->escapeHtml($equipment->iadid); ?></em>'&nbsp;:&nbsp;
    '<em><?php echo $this->escapeHtml($equipment->iaddesc); ?>'</em>?
</p>
<?php
$url = $this->url('equipment', array(
    'action' => 'delete',
    'iadid' => $this->iadid,
));
?>
<form action="<?php echo $url; ?>" method="post">
    <div>
        <input type="hidden" name="iadid" value="<?php echo $equipment->iadid; ?>" />
        <input type="submit" name="del" value="Yes"/>
        <input type="submit" name="del" value="No"/>
    </div>
</form>