<?php

$title = 'Edit category';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'category',
    array(
        'action' => 'edit',
        'iabcode' => $this->iabcode,
    )
));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formRow($form->get('iabcode'));
echo $this->formRow($form->get('iabdesc'));
echo $this->formRow($form->get('iabcolour'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();