<?php

$title = 'Delete feature';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title);?></h1>

<p>Are you sure that you want to delete
    '<?php echo $this->escapeHtml($feature->ibacode); ?>' by
    '<?php echo $this->escapeHtml($feature->ibadesc); ?>'?
</p>
<?php
$url = $this->url('feature', array(
    'action' => 'delete',
    'ibacode' => $this->ibacode,
));
?>
<form action="<?php echo $url; ?>" method="post">
    <div>
        <input type="hidden" name="ibacode" value="<?php echo $feature->ibacode; ?>" />
        <input type="submit" name="del" value="Yes"/>
        <input type="submit" name="del" value="No"/>
    </div>
</form>