<?php

$title = 'Edit feature';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'feature',
    array(
        'action' => 'edit',
        'ibacode'     => $this->ibacode,
    )
));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formRow($form->get('ibacode'));
echo $this->formRow($form->get('ibadesc'));
echo $this->formRow($form->get('ibastartval'));
echo $this->formRow($form->get('ibacost'));
echo $this->formRow($form->get('ibafeatime'));
echo $this->formRow($form->get('ibaactive'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();