<?php

$title = 'Maintain equipment features';
$this->headTitle($title);

function process_array($x_array) {
    foreach ($x_array as $v_arrkey) {
      if (gettype($v_arrkey) == 'object') {
        echo "___found an object in this array with length ".count($v_key).'  '.get_class($v_key).'<br />';
        process_object($v_arrkey);
      } else {
        echo gettype($v_arrkey);
        echo '___ : '.$v_arrkey.'<br />';
      }  
    }
}

function process_object($x_obj) {
    $v_tmpobj = get_object_vars($x_obj);
    echo 'Elements in v_tmpobj is '.count($v_tmpobj).'<br />';
    echo '...type is '.gettype($v_tmpobj).'<br />';
    echo '...length is '.count($v_tmpobj).'<br />';
    if (gettype($v_tmpobj) == 'array')
        process_array($v_tmpobj);
}

function dump_it($x_it) {
    echo gettype($x_it).'<br />';
if (gettype($x_it) == 'object')
    $v_tmp = get_object_vars($x_it);
else
    $v_tmp = $x_it;
echo 'Elements in v_tmp is '.count($v_tmp).'<br />';
echo '...type is '.gettype($v_tmp).'<br />';
echo '...length is '.count($v_tmp).'<br />';
foreach ($v_tmp as $v_key) {
    echo "<hr />";
    if (gettype($v_key) == 'object') {
        echo "found an object with length ".count($v_key).'  '.get_class($v_key).'<br />';
        process_object($v_key);
    } elseif (gettype($v_key) == 'array') {
      echo gettype($v_key);
      echo ' : '.$v_key.' length is '.count($v_key).'<br />';
        process_array($v_key);
    } else {
      echo gettype($v_key);
      echo ' : '.$v_key.'<br />';
    }
}

}

?>
<script lang="text/javascript">
    function showThis(x_this, x_chosen) {
        var v_mychosen = eval(document.getElementById(x_chosen).value);
        if (x_this.className == 'featurecell') {
            x_this.className = 'featurecell_chosen';
            v_mychosen = 1;
            document.getElementById(x_chosen).value = v_mychosen;
        }
        else {
            x_this.className = 'featurecell';
            v_mychosen = 0;
            document.getElementById(x_chosen).value = v_mychosen;
        }
    }
</script>

<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php

$form = $this->form;

$v_equipment = $form->get('efmultiequip');
$v_iadid = $v_equipment->get('iadid');

$form->setAttribute('action', $this->url('equipment', 
                                         array('action' => 'exeaddefme',
                                               'iadid' => $v_equipment->get('iadid'))));
$form->prepare();


$v_features = $v_equipment->get('availfeatures');
$v_attr = $v_features->getValue();
$v_featureset = $v_attr["featureset"];
?>
<div id="topdiv" style=" width:'100%';height:'100px'">
    <table width="100%" border="0" cellspacing="0" cellpadding="0">
        <tr>
            <td style="width:40%"><h2>Equipment Code:</h2></td>
            <td><h2><span class="inputfield"><?php echo $v_iadid->getValue()?></span></h2></td>
        </tr>
    </table>
</div>
<?php
echo $this->form()->openTag($form);
echo $this->formHidden($v_equipment->get('iadid'));

?>
<div id="maincontent" style="width:100%;height:100%">
    <table cellspacing="0" cellpadding="4" border="0" width="100%">
        <tr>
<?php
  $v_column_count = 0;
  $v_max_columns = 4;
  foreach ($v_featureset as $v_featurerec) {
      if ($v_column_count % $v_max_columns == 0) {
?>      </tr>
        <tr>
<?php
      }
?>
            <td width="24%">
<!-- chosen from db = <?php echo $v_featurerec['chosen'] ?> -->
                <div class="featurecell<?php if ($v_featurerec['chosen'] == 1) echo '_chosen'?>" style="width:100%; height:100%" onClick="showThis(this, 'chosen_<?php echo $v_column_count ?>');">
                    <fieldset name="<?php echo $v_column_count?>">
(<input type="hidden" name="ibacode_<?php echo $v_column_count?>" value="<?php echo $v_featurerec['ibacode']; ?>"><?php echo $v_featurerec['ibacode']; ?>)&nbsp; <input type="hidden" value="<?php echo $v_featurerec['ibadesc']?>"><?php echo $v_featurerec['ibadesc']?><br />
                <input type="hidden" value="<?php echo $v_featurerec['ibacost']?>">Cost: <?php echo $v_featurerec['ibacost']?><br />
                <input type="hidden" value="<?php echo $v_featurerec['ibastartval']?>">Execution Time: <?php echo $v_featurerec['ibastartval']?>
                <input id="chosen_<?php echo $v_column_count?>" type="hidden" name="chosen_<?php echo $v_column_count?>" value="<?php echo $v_featurerec['chosen'] ?>">
                    </fieldset>
                </div>
            </td>
<?php
      $v_column_count = $v_column_count + 1;
  }
  echo "</tr>";
?>
   </table>
<?php
echo "&nbsp;".$this->formSubmit($form->get('submit'));
echo '&nbsp;<input type="submit" name="cancel" value="Cancel">';
echo $this->form()->closeTag();
?>
    
</div>