<?php

$title = 'Edit equipment';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'equipment',
    array(
        'action' => 'edit',
        'iadid' => $this->iadid,
    )
));

$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('iadid'));
echo $this->formRow($form->get('iaddesc'));
echo $this->formRow($form->get('iadbld'));
echo $this->formRow($form->get('iadloc'));
echo $this->formRow($form->get('iadinstype'));
echo $this->formRow($form->get('iadcat'));
echo "Active&nbsp;". $this->FormRadioTwb($form->get('iadactive'), \DluTwBootstrap\Form\FormUtil::FORM_TYPE_HORIZONTAL, array('inline'=>true));
echo $this->formRow($form->get('iadcontact'));
echo $this->formRow($form->get('iadnotes'));
echo "Send booking email&nbsp;".$this->FormRadioTwb($form->get('iademailonbooking'), \DluTwBootstrap\Form\FormUtil::FORM_TYPE_HORIZONTAL, array('inline'=>true));
echo $this->formRow($form->get('iadslots'));
echo $this->formSubmit($form->get('submit'));
echo $this->formSubmit($form->get('cancel'));
echo $this->form()->closeTag();